<?php
require __DIR__.'/_ui.php'; cms_require('modules');
$types=cms_entry_types(); $kind=(string)($_GET['kind']??'news'); if (!isset($types[$kind])) $kind='news';
$id=(int)($_GET['id']??0); $edit=isset($_GET['new']) || $id;
$entry=$id?cms_row('SELECT * FROM content_entries WHERE id=? AND kind=?',[$id,$kind]):null;
if ($id && !$entry) { http_response_code(404); exit('Eintrag nicht gefunden.'); }
$entry=$entry??[]; $extra=json_decode($entry['data_json']??'{}',true)?:[];
if (!empty($_SESSION['failed_entry']) && ($_SESSION['failed_entry']['kind']??'')===$kind && (int)($_SESSION['failed_entry']['id']??0)===$id) { $entry=array_merge($entry,$_SESSION['failed_entry']); $extra=array_merge($extra,$_SESSION['failed_entry']); unset($_SESSION['failed_entry']); }
ui_start($edit?($id?'Eintrag bearbeiten':'Neuer Eintrag'):$types[$kind],'Zentrale Inhalte für Listen, Detailseiten, Suche und wiederverwendbare Blöcke.',ui_link($edit?'← Zur Sammlung':'＋ Eintrag erstellen',$edit?'/admin/content.php?kind='.$kind:'/admin/content.php?kind='.$kind.'&new=1',$edit?'btn-secondary':'btn-primary'));
?><nav class="workspace-tabs" aria-label="Inhaltstypen"><?php foreach ($types as $k=>$label): ?><a class="<?= $kind===$k?'active':'' ?>" href="<?= e(site_url('/admin/content.php?kind='.$k)) ?>"><?= e($label) ?></a><?php endforeach; ?></nav><?php
if ($edit): ?><section class="workspace-card"><?php ui_form_start('entry.save','/admin/content.php?kind='.$kind.($id?'&id='.$id:'&new=1'),['id'=>$id,'kind'=>$kind]);
ui_field('title','Titel',$entry['title']??'','text','',true); ?><div class="form-grid"><?php ui_field('slug','URL-Kürzel',$entry['slug']??'','text','Leer lassen, um es aus dem Titel zu erzeugen.'); ui_select('status','Sichtbarkeit',['draft'=>'Entwurf','published'=>'Veröffentlicht'],$entry['status']??'draft'); ?></div><?php
ui_field('summary','Kurzbeschreibung',$entry['summary']??'','textarea'); ui_field('body','Inhalt',$entry['body']??'','textarea','Absätze und Zeilenumbrüche bleiben erhalten.');
?><div class="form-grid"><?php ui_field('category','Kategorie / Thema',$entry['category']??''); ui_field('language','Sprache',$entry['language']??'de'); ui_field('starts_at',$kind==='event'?'Veranstaltungsbeginn':'Veröffentlichen ab',$entry['starts_at']??'','datetime-local'); ui_field('ends_at',$kind==='event'?'Veranstaltungsende':'Veröffentlichen bis',$entry['ends_at']??'','datetime-local'); ?></div>
<details open><summary>Weitere Angaben</summary><div class="form-grid"><?php
$fields=['image'=>'Bild-URL','url'=>'Weiterführender Link'];
if (in_array($kind,['event','directory','job','accommodation','service'])) $fields+=['location'=>'Ort / Einrichtung','address'=>'Adresse','email'=>'Kontakt-E-Mail','phone'=>'Telefon','organizer'=>'Veranstalter / Träger','price'=>'Preis / Vergütung','latitude'=>'Breitengrad','longitude'=>'Längengrad'];
foreach ($fields as $k=>$label) ui_field($k,$label,$extra[$k]??'',in_array($k,['image','url'])?'url':($k==='email'?'email':'text'));
?></div><?php if ($kind==='poll') ui_field('options','Antwortmöglichkeiten',$extra['options']??"Ja\nNein",'textarea','Eine Option pro Zeile. Nach der ersten Stimme bleiben die Optionen unveränderlich.'); ?></details><?php ui_submit(); ?></section><?php
else: $entries=cms_entries($kind); ?>
<div class="workspace-toolbar"><input class="input" aria-label="Einträge filtern" placeholder="Titel, Kategorie oder Sprache suchen …" data-filter-input="entryList"><?= ui_link('Öffentliche Ansicht ↗','/modules.php?kind='.$kind) ?><?php if ($kind==='event') echo ui_link('Kalender exportieren','/feed.php?format=ics'); if ($kind==='news') echo ui_link('RSS-Feed','/feed.php?format=rss'); ?></div>
<section class="workspace-card"><div class="table-scroll"><table class="workspace-table" id="entryList"><thead><tr><th>Titel</th><th>Kategorie</th><th>Sprache</th><th>Status</th><th>Aktionen</th></tr></thead><tbody><?php foreach ($entries as $row): ?><tr data-search="<?= e($row['title'].' '.$row['category'].' '.$row['language']) ?>"><td><a href="<?= e(site_url('/admin/content.php?kind='.$kind.'&id='.$row['id'])) ?>"><strong><?= e($row['title']) ?></strong></a><small><?= e($row['starts_at']??'') ?></small></td><td><?= e($row['category']??'—') ?></td><td><?= e($row['language']) ?></td><td><?= ui_badge($row['status']) ?></td><td><?php ui_form_start('entry.copy','/admin/content.php?kind='.$kind,['id'=>$row['id']]); ui_submit('Duplizieren'); ?></td></tr><?php endforeach; ?></tbody></table></div><?php if (!$entries) ui_empty('Noch keine Einträge','Erstellen Sie einen Eintrag und binden Sie die Sammlung mit dem Block „Sammlung“ auf beliebigen Seiten ein.'); ?></section>
<?php if ($kind==='newsletter'): ?><section class="workspace-card"><h2>Abonnenten</h2><p class="workspace-note">Anmeldungen werden erst nach Bestätigung aktiviert. Versand erfolgt nach Export über Ihren Newsletter-Dienst.</p><?= ui_link('Bestätigte Adressen exportieren','/admin/export.php?type=subscribers') ?><table class="workspace-table"><thead><tr><th>E-Mail</th><th>Status</th><th>Aktion</th></tr></thead><tbody><?php foreach (cms_rows('SELECT id,email,status FROM newsletter_subscribers ORDER BY id DESC LIMIT 100') as $s): ?><tr><td><?= e($s['email']) ?></td><td><?= e($s['status']) ?></td><td><?php ui_form_start('subscriber.remove','/admin/content.php?kind=newsletter',['id'=>$s['id']]); ui_submit('Abmelden'); ?></td></tr><?php endforeach; ?></tbody></table></section><?php endif;
endif; ui_end();
