<?php
require __DIR__.'/_ui.php';
$pages=array_values(array_filter(fetch_pages(),fn($p)=>cms_can_page((int)$p['id'])));
$review=array_values(array_filter($pages,fn($p)=>$p['status']==='review'));
$scheduled=array_values(array_filter($pages,fn($p)=>$p['status']==='published' && $p['publish_at'] && $p['publish_at']>cms_now()));
$tasks=cms_rows("SELECT t.*,u.username FROM tasks t LEFT JOIN users u ON u.id=t.assigned_to WHERE t.status<>'done' AND (t.assigned_to=? OR t.created_by=?) ORDER BY CASE WHEN t.due_at IS NULL THEN 1 ELSE 0 END,t.due_at",[current_user()['id'],current_user()['id']]);
ui_start('Alles im Blick.','Willkommen zurück, '.current_user()['username'].'. Hier beginnt Ihr nächster guter Inhalt.',cms_can('edit')?ui_link('＋ Neue Seite','/admin/editor.php','btn-primary'):'');
?>
<div class="dashboard-welcome"><div><span class="eyebrow">IHR REDAKTIONELLER ARBEITSPLATZ</span><h2>Gute Inhalte.<br>Gemeinsam veröffentlicht.</h2><p>Von der ersten Idee bis zur fertigen Seite: Inhalte, Team und Termine an einem Ort.</p><?= ui_link('Seiten verwalten →','/admin/','btn-primary') ?></div><div class="welcome-art" aria-hidden="true"><div class="art-card art-back"></div><div class="art-card"><div class="art-dots">● ● ●</div><div class="art-line"></div><div class="art-line short"></div><div class="art-grid"><span></span><span></span><span></span></div><div class="art-check">✓</div></div></div></div>
<div class="metric-grid"><?php foreach ([['Seiten',count($pages),'Alle Inhalte','/admin/'],['Zur Freigabe',count($review),'Gemeinsam prüfen','/admin/workspace.php?view=tasks'],['Geplant',count($scheduled),'Zeitpunkt im Blick','/admin/workspace.php?view=tasks'],['Meine Aufgaben',count($tasks),'Nächste Schritte','/admin/workspace.php?view=tasks']] as [$label,$count,$hint,$url]): ?><a class="metric-card" href="<?= e(site_url($url)) ?>"><span><?= e($label) ?></span><strong><?= $count ?></strong><small><?= e($hint) ?> ↗</small></a><?php endforeach; ?></div>
<div class="workspace-columns"><section class="workspace-card"><div class="card-heading"><h2>Zuletzt bearbeitet</h2><?= ui_link('Alle Seiten','/admin/','btn-ghost btn-sm') ?></div><?php usort($pages,fn($a,$b)=>strcmp($b['updated_at']??'',$a['updated_at']??'')); foreach (array_slice($pages,0,6) as $p): ?><a class="workspace-row" href="<?= e(site_url('/admin/editor.php?id='.$p['id'])) ?>"><span class="row-symbol">▤</span><span class="row-main"><strong><?= e($p['title']) ?></strong><small>/<?= e($p['slug']) ?></small></span><?= ui_badge($p['status']) ?><span>→</span></a><?php endforeach; if (!$pages) ui_empty('Platz für Ihre Ideen','Erstellen Sie Ihre erste Seite.'); ?></section>
<section class="workspace-card"><div class="card-heading"><h2>Ihre nächsten Schritte</h2></div><?php foreach (array_slice($tasks,0,5) as $t): ?><a class="workspace-row" href="<?= e(site_url('/admin/workspace.php?view=tasks')) ?>"><span class="task-marker"></span><span class="row-main"><strong><?= e($t['title']) ?></strong><small><?= e($t['due_at']?date('d.m.Y',strtotime($t['due_at'])):'Ohne Termin') ?></small></span><?= ui_badge($t['status']) ?></a><?php endforeach; if (!$tasks) ui_empty('Alles aufgeräumt','Neue Aufgaben helfen Ihrem Team, die nächsten Schritte zu planen.'); ?><?= ui_link('Aufgabe erstellen →','/admin/workspace.php?view=tasks','btn-ghost') ?></section></div>
<?php if (cms_can('modules')): ?><div class="section-heading"><h2>Mehr Möglichkeiten für Ihre Website</h2><p>Inhalte einmal pflegen, an vielen Stellen verwenden.</p></div><div class="module-grid"><?php foreach ([['event','Veranstaltungen','Termine veröffentlichen und als Kalender teilen.','◷'],['news','Nachrichten','Aktuelles zentral pflegen und auf Seiten einbinden.','▤'],['directory','Verzeichnisse','Menschen, Vereine und Einrichtungen auffindbar machen.','◎']] as [$kind,$title,$desc,$icon]): ?><a class="module-card" href="<?= e(site_url('/admin/content.php?kind='.$kind)) ?>"><span class="module-icon"><?= $icon ?></span><h3><?= e($title) ?></h3><p><?= e($desc) ?></p><span>Öffnen →</span></a><?php endforeach; ?></div><?php endif; ?>
<?php ui_end();
