<?php
require __DIR__.'/_ui.php'; cms_require('forms');
$id=(int)($_GET['id']??0); $edit=$id || isset($_GET['new']);
$form=$id?cms_row('SELECT * FROM cms_forms WHERE id=?',[$id]):[];
if ($id && !$form) { http_response_code(404); exit('Formular nicht gefunden.'); }
$fields=json_decode($form['fields_json']??'[]',true)?:[['label'=>'Name','type'=>'text','required'=>true],['label'=>'E-Mail','type'=>'email','required'=>true],['label'=>'Nachricht','type'=>'textarea']];
if (isset($_SESSION['failed_form']) && (int)($_SESSION['failed_form']['id']??0)===$id) { $form=array_merge($form,$_SESSION['failed_form']); $fields=$form['fields']??$fields; unset($_SESSION['failed_form']); }
function ui_builder_field(array $f=[]): void { ?><div class="field-builder-row" data-field-row><div class="form-grid"><label>Beschriftung<input class="input" data-key="label" value="<?= e($f['label']??'') ?>" required></label><label>Feldtyp<select class="select" data-key="type"><?php foreach (['text'=>'Text','email'=>'E-Mail','textarea'=>'Mehrzeilig','tel'=>'Telefon','number'=>'Zahl','date'=>'Datum','select'=>'Auswahl','checkbox'=>'Kontrollkästchen'] as $type=>$label): ?><option value="<?= $type ?>" <?= ($f['type']??'text')===$type?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label><label>Platzhalter<input class="input" data-key="placeholder" value="<?= e($f['placeholder']??'') ?>"></label><label>Auswahloptionen (mit | trennen)<input class="input" data-key="options" value="<?= e($f['options']??'') ?>" placeholder="Option A | Option B"></label></div><div class="field-controls"><label><input type="checkbox" data-key="required" value="1" <?= !empty($f['required'])?'checked':'' ?>> Pflichtfeld</label><button class="btn btn-ghost" type="button" data-field-action="up" aria-label="Feld nach oben">↑</button><button class="btn btn-ghost" type="button" data-field-action="down" aria-label="Feld nach unten">↓</button><button class="btn btn-ghost" type="button" data-field-action="delete">Entfernen</button></div></div><?php }
ui_start($edit?'Formular gestalten':'Formulare','Felder zusammenstellen, veröffentlichen und Einsendungen zentral bearbeiten.',ui_link($edit?'← Alle Formulare':'＋ Formular erstellen',$edit?'/admin/forms.php':'/admin/forms.php?new=1','btn-primary'));
if ($edit): ?><section class="workspace-card"><?php ui_form_start('form.save','/admin/forms.php'.($id?'?id='.$id:'?new=1'),['id'=>$id]); ui_field('title','Formulartitel',$form['title']??'','text','',true); ui_field('description','Einleitung',$form['description']??'','textarea'); ui_select('status','Sichtbarkeit',['draft'=>'Entwurf','published'=>'Veröffentlicht'],$form['status']??'draft'); ?><div data-form-builder><h2>Formularfelder</h2><div data-fields><?php foreach ($fields as $f) ui_builder_field($f); ?></div><button class="btn btn-secondary" type="button" data-add-field>＋ Feld hinzufügen</button><template><?php ui_builder_field(); ?></template></div><?php ui_field('success_message','Bestätigung nach dem Absenden',$form['success_message']??'Vielen Dank! Ihre Nachricht ist bei uns eingegangen.'); ui_submit('Formular speichern'); ?></section><?php
else: $forms=cms_rows('SELECT f.*, (SELECT COUNT(*) FROM form_submissions s WHERE s.form_id=f.id) AS submissions FROM cms_forms f ORDER BY id DESC'); ?><div class="module-grid"><?php foreach ($forms as $f): ?><article class="module-card"><span class="module-icon">☷</span><h3><?= e($f['title']) ?></h3><p><?= count(json_decode($f['fields_json'],true)) ?> Felder · <?= (int)$f['submissions'] ?> Einsendungen · ID <?= (int)$f['id'] ?></p><?= ui_badge($f['status']) ?><div class="action-row" style="margin-top:18px"><?= ui_link('Bearbeiten','/admin/forms.php?id='.$f['id']) ?><?= ui_link('Ansehen','/modules.php?form='.$f['id'],'btn-ghost') ?></div></article><?php endforeach; ?></div><?php if (!$forms) ui_empty('Ihr erstes Formular','Erstellen Sie ein Kontaktformular, eine Anmeldung oder eine Anfrage. Einsendungen landen im Posteingang.'); ?>
<p class="workspace-note">Im Seiteneditor können Sie ein gespeichertes Formular über den Block „Formular einbinden“ auswählen. Die bisherigen Formularblöcke speichern jetzt ebenfalls echte Einsendungen.</p><?php endif; ui_end();
