<?php
require __DIR__.'/_ui.php';
$id=(int)($_GET['id']??0);
try { $page=cms_assert_page($id); } catch (Throwable $e) { http_response_code(403); exit(e($e->getMessage())); }
ui_start('Versionen & Zusammenarbeit',$page['title'].' · Änderungen nachvollziehen und als Entwurf wiederherstellen.',ui_link('← Zum Editor','/admin/editor.php?id='.$id));
$revisions=cms_rows('SELECT r.*,u.username FROM page_revisions r LEFT JOIN users u ON u.id=r.user_id WHERE r.page_id=? ORDER BY r.id DESC LIMIT 100',[$id]);
?><div class="workspace-columns"><section class="workspace-card"><h2>Versionsverlauf</h2><?php foreach ($revisions as $r): $snapshot=json_decode($r['snapshot_json'],true); ?><details class="workspace-row" style="display:block"><summary><?= e($r['created_at'].' · '.($r['username']??'Gelöschter Benutzer').' · '.$r['note']) ?></summary><p class="workspace-note"><?= e($snapshot['title']) ?> · <?= count(json_decode($snapshot['blocks_json']??'[]',true)?:[]) ?> Blöcke · <?= e(cms_statuses()[$snapshot['status']]??$snapshot['status']) ?></p><pre class="revision-content"><?= e(json_encode(json_decode($snapshot['blocks_json'],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?></pre><?php ui_form_start('revision.restore','/admin/history.php?id='.$id,['id'=>$r['id'],'version'=>$page['version']]); ui_submit('Als Entwurf wiederherstellen'); ?></details><?php endforeach; if (!$revisions) ui_empty('Noch keine früheren Versionen','Beim nächsten Speichern wird der aktuelle Stand hier gesichert.'); ?></section>
<section class="workspace-card"><h2>Redaktionsnotizen</h2><?php foreach (cms_rows('SELECT c.*,u.username FROM page_comments c LEFT JOIN users u ON c.user_id=u.id WHERE page_id=? ORDER BY c.id DESC',[$id]) as $c): ?><div class="workspace-row" style="display:block"><strong><?= e($c['username']??'Gelöschter Benutzer') ?></strong><p><?= nl2br(e($c['body'])) ?></p><small><?= e($c['created_at']) ?></small></div><?php endforeach; ui_form_start('page.comment','/admin/history.php?id='.$id,['id'=>$id]); ui_field('body','Notiz hinzufügen','','textarea','Nur für die Redaktion sichtbar.',true); ui_submit('Notiz speichern'); ?></section></div>
<section class="workspace-card"><h2>Seite wiederverwenden</h2><div class="form-grid"><div><?php ui_form_start('page.copy','/admin/history.php?id='.$id,['id'=>$id]); ui_submit('Seite duplizieren'); ?></div><div><?php ui_form_start('page.translate','/admin/history.php?id='.$id,['id'=>$id]); ui_field('language','Neue Sprachfassung','en','text','Erzeugt eine verknüpfte Kopie für Ihre manuelle Übersetzung.'); ui_submit('Sprachfassung anlegen'); ?></div></div></section><?php ui_end();
