<?php
require __DIR__.'/_ui.php';
$views=['tasks'=>'Aufgaben & Freigaben','inbox'=>'Posteingang','templates'=>'Vorlagen','seo'=>'Suche & Weiterleitungen','analytics'=>'Statistik','trash'=>'Papierkorb','system'=>'Daten & Schnittstellen'];
$view=(string)($_GET['view']??'tasks'); if (!isset($views[$view])) $view='tasks';
if ($view==='system') require_admin(); elseif ($view==='inbox') cms_require('forms'); else cms_require('edit');
$return='/admin/workspace.php?view='.$view;
ui_start($views[$view],['tasks'=>'Redaktion planen, Beiträge prüfen und Veröffentlichungen vorbereiten.','inbox'=>'Einsendungen und öffentliche Kommentare gemeinsam bearbeiten.','templates'=>'Bewährte Seitenaufbauten als Ausgangspunkt für neue Inhalte.','seo'=>'Auffindbarkeit, Seitenqualität und bestehende Links im Blick.','analytics'=>'Seitenaufrufe als Tageswerte ohne Besucherprofile.','trash'=>'Gelöschte Seiten sicher als Entwurf wiederherstellen.','system'=>'Inhalte austauschen und Ihre Website konfigurieren.'][$view]);
if ($view==='tasks'):
    $pages=array_values(array_filter(fetch_pages(),fn($p)=>cms_can_page((int)$p['id'])));
    $tasks=is_admin()?cms_rows('SELECT t.*,u.username FROM tasks t LEFT JOIN users u ON t.assigned_to=u.id ORDER BY t.id DESC LIMIT 100'):cms_rows('SELECT t.*,u.username FROM tasks t LEFT JOIN users u ON t.assigned_to=u.id WHERE t.created_by=? OR t.assigned_to=? ORDER BY t.id DESC LIMIT 100',[current_user()['id'],current_user()['id']]);
    ?><div class="workspace-columns"><div><section class="workspace-card"><h2>Aufgaben</h2><?php foreach ($tasks as $t): ?><div class="workspace-row"><div class="row-main"><strong><?= e($t['title']) ?></strong><small><?= e(($t['username']??'Nicht zugewiesen').' · '.($t['due_at']??'Ohne Termin')) ?></small><p><?= nl2br(e($t['body']??'')) ?></p><?php if ($t['page_id'] && cms_can_page((int)$t['page_id'])) echo ui_link('Seite öffnen','/admin/editor.php?id='.$t['page_id'],'btn-ghost btn-sm'); ?></div><?php ui_form_start('task.status',$return,['id'=>$t['id']]); ui_select('status','Status',['open'=>'Offen','doing'=>'In Arbeit','done'=>'Erledigt'],$t['status']); ui_submit('Aktualisieren'); ?></div><?php endforeach; if (!$tasks) ui_empty('Noch keine Aufgaben','Erstellen Sie eine Aufgabe für sich oder Ihr Team.'); ?></section><section class="workspace-card"><h2>Freigaben & Zeitplan</h2><?php $count=0; foreach ($pages as $p) { if ($p['status']!=='review' && !($p['status']==='published' && $p['publish_at'] && $p['publish_at']>cms_now())) continue; $count++; ?><a class="workspace-row" href="<?= e(site_url('/admin/editor.php?id='.$p['id'])) ?>"><span class="row-main"><strong><?= e($p['title']) ?></strong><small><?= e($p['publish_at']??'Wartet auf Prüfung') ?></small></span><?= ui_badge($p['status']) ?></a><?php } if (!$count) ui_empty('Keine offenen Freigaben','Seiten zur Prüfung und geplante Veröffentlichungen erscheinen hier.'); ?></section></div>
    <section class="workspace-card"><h2>Neue Aufgabe</h2><?php ui_form_start('task.save',$return); ui_field('title','Was ist zu tun?','','text','',true); ui_field('body','Beschreibung','','textarea'); ui_select('assigned_to','Verantwortlich',[''=>'Nicht zugewiesen']+array_column(cms_rows("SELECT id,username FROM users WHERE role<>'viewer' ORDER BY username"),'username','id'),current_user()['id']); ui_select('page_id','Zugehörige Seite',[''=>'Keine']+array_column($pages,'title','id')); ui_field('due_at','Fällig am','','date'); ui_submit('Aufgabe erstellen'); ?></section></div><?php
elseif ($view==='inbox'):
    $status=(string)($_GET['status']??'new'); if (!in_array($status,['new','read','done','spam','all'],true)) $status='new';
    ?><nav class="workspace-tabs"><?php foreach (['new'=>'Neu','read'=>'Gelesen','done'=>'Erledigt','spam'=>'Spam','all'=>'Alle'] as $key=>$label): ?><a class="<?= $key===$status?'active':'' ?>" href="<?= e(site_url($return.'&status='.$key)) ?>"><?= $label ?></a><?php endforeach; ?></nav><div class="workspace-toolbar"><?= ui_link('Einsendungen als CSV','/admin/export.php?type=submissions') ?></div><section class="workspace-card"><?php
    $rows=cms_rows('SELECT * FROM form_submissions'.($status==='all'?'':' WHERE status=?').' ORDER BY id DESC LIMIT 100',$status==='all'?[]:[$status]);
    foreach ($rows as $r): ?><details class="workspace-row" style="display:block"><summary><strong><?= e($r['title']??'Formular') ?></strong> · <?= e($r['created_at']) ?> <?= ui_badge($r['status']) ?></summary><dl><?php foreach (json_decode($r['data_json'],true)?:[] as $field): ?><dt><strong><?= e($field['label']) ?></strong></dt><dd style="white-space:pre-wrap"><?= e($field['value']) ?></dd><?php endforeach; ?></dl><div class="form-grid"><div><?php ui_form_start('submission.status',$return,['id'=>$r['id']]); ui_select('status','Bearbeitungsstatus',['new'=>'Neu','read'=>'Gelesen','done'=>'Erledigt','spam'=>'Spam'],$r['status']); ui_submit(); ?></div><div><form method="post" action="<?= e(site_url('/admin/action.php')) ?>" data-confirm-native="Diese Einsendung endgültig entfernen?"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="submission.delete"><input type="hidden" name="return_to" value="<?= e($return) ?>"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-danger">Endgültig löschen</button></form></div></div></details><?php endforeach; if (!$rows) ui_empty('Keine Einsendungen in dieser Ansicht','Neue Antworten Ihrer Website-Besucher erscheinen hier.'); ?></section>
    <?php if (cms_can('modules')): ?><section class="workspace-card"><h2>Öffentliche Kommentare prüfen</h2><?php foreach (cms_rows("SELECT c.*,e.title FROM public_comments c JOIN content_entries e ON e.id=c.entry_id WHERE c.status='pending' ORDER BY c.id DESC LIMIT 100") as $c): ?><div class="workspace-row" style="display:block"><strong><?= e($c['author'].' · '.$c['title']) ?></strong><p><?= nl2br(e($c['body'])) ?></p><?php ui_form_start('comment.moderate',$return,['id'=>$c['id']]); ui_select('status','Entscheidung',['approved'=>'Veröffentlichen','spam'=>'Ablehnen']); ui_submit('Moderation speichern'); ?></div><?php endforeach; ?></section><?php endif;
elseif ($view==='templates'):
    ?><div class="workspace-columns"><section class="workspace-card"><h2>Gespeicherte Vorlagen</h2><?php $templates=cms_rows('SELECT * FROM content_templates ORDER BY title'); foreach ($templates as $t): ?><div class="workspace-row"><div class="row-main"><strong><?= e($t['title']) ?></strong><small><?= e($t['description']??'') ?> · ID <?= (int)$t['id'] ?></small></div><?php ui_form_start('template.use',$return,['id'=>$t['id']]); if (!is_admin() && cms_rows('SELECT page_id FROM user_scopes WHERE user_id=?',[current_user()['id']])) ui_select('parent_id','Unter Seite',array_column(array_filter(fetch_pages(),fn($p)=>cms_can_page((int)$p['id'])),'title','id')); ui_submit('Neue Seite daraus'); ?></div><?php endforeach; if (!$templates) ui_empty('Wissen wiederverwenden','Speichern Sie einen bewährten Seitenaufbau als Vorlage.'); ?></section><section class="workspace-card"><h2>Vorlage aus Seite erstellen</h2><?php ui_form_start('template.save',$return); ui_field('title','Name der Vorlage','','text','',true); ui_field('description','Kurze Beschreibung'); ui_select('page_id','Seite',array_column(array_filter(fetch_pages(),fn($p)=>cms_can_page((int)$p['id'])),'title','id')); ui_submit('Vorlage speichern'); ?><p class="workspace-note">Eine neue Seite erhält eine unabhängige Kopie. Mit dem Block „Geteilte Inhalte“ können Sie stattdessen den jeweils veröffentlichten Inhalt einer Quellseite anzeigen.</p></section></div><?php
elseif ($view==='trash'):
    ?><section class="workspace-card"><?php $rows=array_filter(cms_rows('SELECT * FROM pages WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC'),fn($p)=>cms_can_page((int)$p['id'])); foreach ($rows as $p): ?><div class="workspace-row"><span class="row-main"><strong><?= e($p['title']) ?></strong><small><?= e($p['deleted_at']) ?> · /<?= e($p['slug']) ?></small></span><?php ui_form_start('page.restore',$return,['id'=>$p['id']]); ui_submit('Wiederherstellen'); ?></div><?php endforeach; if (!$rows) ui_empty('Der Papierkorb ist leer','Entfernte Seiten bleiben hier erhalten. Stellen Sie übergeordnete Seiten zuerst wieder her.'); ?></section><?php
elseif ($view==='seo'):
    ?><div class="workspace-toolbar"><?= ui_link('Website durchsuchen','/search.php') ?><?= ui_link('Sitemap öffnen','/sitemap.php') ?><?= ui_link('RSS-Feed','/feed.php?format=rss') ?></div><section class="workspace-card"><h2>Seitenqualität</h2><div class="table-scroll"><table class="workspace-table"><thead><tr><th>Seite</th><th>Beschreibung</th><th>Hinweise</th></tr></thead><tbody><?php foreach (fetch_pages() as $p): if (!cms_can_page((int)$p['id'])) continue; $issues=[]; $len=function_exists('mb_strlen')?mb_strlen($p['meta_description']??''):strlen($p['meta_description']??''); if ($len<50) $issues[]='Beschreibung ergänzen'; if ($len>160) $issues[]='Beschreibung kürzen'; if ($p['noindex']) $issues[]='Von Suchmaschinen ausgeschlossen'; foreach (json_decode($p['blocks_json']??'[]',true)?:[] as $block) if ($block['type']==='image' && empty($block['settings']['alt'])) $issues[]='Bild ohne Alternativtext'; ?><tr><td><a href="<?= e(site_url('/admin/editor.php?id='.$p['id'])) ?>"><?= e($p['title']) ?></a></td><td><?= $len ?> Zeichen</td><td><?= e(implode(' · ',array_unique($issues))?:'Grundangaben vollständig') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
    <?php if (is_admin()): ?><div class="workspace-columns"><section class="workspace-card"><h2>Weiterleitungen</h2><?php foreach (cms_rows('SELECT * FROM redirects ORDER BY source_path') as $r): ?><div class="workspace-row"><span class="row-main"><strong><?= e($r['source_path'].' → '.$r['target_path']) ?></strong><small>HTTP <?= (int)$r['http_code'] ?></small></span><?php ui_form_start('redirect.delete',$return,['id'=>$r['id']]); ui_submit('Entfernen'); ?></div><?php endforeach; ?></section><section class="workspace-card"><h2>Weiterleitung hinzufügen</h2><?php ui_form_start('redirect.save',$return); ui_field('source_path','Alter Pfad','/alter-name'); ui_field('target_path','Neuer Pfad','/neuer-name'); ui_select('http_code','Art',['301'=>'301 · Dauerhaft','302'=>'302 · Vorübergehend']); ui_submit(); ?></section></div><?php endif;
elseif ($view==='analytics'):
    $since=date('Y-m-d',strtotime('-29 days')); $visibleIds=array_column(array_filter(fetch_pages(),fn($p)=>cms_can_page((int)$p['id'])),'id');
    $stats=$visibleIds?cms_rows('SELECT v.page_id,p.title,SUM(v.views) AS total FROM page_views v JOIN pages p ON p.id=v.page_id WHERE v.view_date>=? AND v.page_id IN ('.implode(',',array_fill(0,count($visibleIds),'?')).') GROUP BY v.page_id,p.title ORDER BY total DESC',array_merge([$since],$visibleIds)):[];
    $daily=$visibleIds?cms_rows('SELECT view_date,SUM(views) AS total FROM page_views WHERE view_date>=? AND page_id IN ('.implode(',',array_fill(0,count($visibleIds),'?')).') GROUP BY view_date',array_merge([$since],$visibleIds)):[]; $values=array_column($daily,'total','view_date'); $max=max(array_merge([1],array_values($values)));
    ?><section class="workspace-card"><h2><?= (int)array_sum(array_column($stats,'total')) ?> Aufrufe in den letzten 30 Tagen</h2><div class="bar-chart" role="img" aria-label="Seitenaufrufe pro Tag; genaue Werte folgen als Tabelle"><?php for ($i=29;$i>=0;$i--): $date=date('Y-m-d',strtotime('-'.$i.' days')); $count=(int)($values[$date]??0); ?><div class="bar" style="height:<?= max(2,round(100*$count/$max)) ?>%" title="<?= e($date) ?>: <?= $count ?>"></div><?php endfor; ?></div><details><summary>Tageswerte anzeigen</summary><table class="workspace-table"><thead><tr><th>Datum</th><th>Aufrufe</th></tr></thead><tbody><?php foreach ($daily as $day): ?><tr><td><?= e($day['view_date']) ?></td><td><?= (int)$day['total'] ?></td></tr><?php endforeach; ?></tbody></table></details></section><section class="workspace-card"><h2>Seitenaufrufe</h2><table class="workspace-table"><thead><tr><th>Seite</th><th>Aufrufe</th></tr></thead><tbody><?php foreach ($stats as $row): ?><tr><td><?= e($row['title']) ?></td><td><?= (int)$row['total'] ?></td></tr><?php endforeach; ?></tbody></table><?php if (!$stats) ui_empty('Noch keine Daten','Die Aufrufzählung lässt sich unter Daten & Schnittstellen aktivieren.'); ?><p class="workspace-note">Gezählt werden erfolgreiche öffentliche Seitenaufrufe, einschließlich möglicher Bots. Es werden keine IP-Adressen, Besucherkennungen oder Klickpfade gespeichert. Angemeldete Redakteure und Vorschauen zählen nicht mit.</p></section><?php
elseif ($view==='system'):
    ?><div class="workspace-columns"><div><section class="workspace-card"><h2>Daten exportieren</h2><p class="workspace-note">Der Inhaltsexport enthält Seiten, Versionen, Sammlungen, Vorlagen und Formulardefinitionen. Benutzerdaten, Einsendungen, Zugangsdaten und hochgeladene Dateien werden nicht exportiert. Für ein vollständiges Backup zusätzlich Datenbank und Upload-Ordner sichern.</p><?= ui_link('Inhaltsexport herunterladen','/admin/export.php?type=content','btn-primary') ?></section><section class="workspace-card"><h2>Sammlungen importieren</h2><?php ui_form_start('content.import',$return); ui_field('json','JSON-Daten','','textarea','Einträge aus einem WebCMS-Export oder eine Liste mit kind, title, summary, body, category. Der Import legt neue Entwürfe an.',true); ui_submit('Als Entwürfe importieren'); ?></section><section class="workspace-card"><h2>Kalender importieren</h2><?php ui_form_start('calendar.import',$return); ui_field('ics','iCalendar-Inhalt (.ics)','','textarea','Einzeltermine mit SUMMARY und DTSTART. Wiederholungen und nicht unterstützte Zeitzonen werden mit einer Fehlermeldung abgelehnt.',true); ui_submit('Termine importieren'); ?></section></div><div><section class="workspace-card"><h2>Website-Betrieb</h2><?php ui_form_start('system.save',$return); ui_select('timezone','Zeitzone',array_combine(timezone_identifiers_list(),timezone_identifiers_list()),setting('timezone','Europe/Berlin')); ui_field('newsletter_sender','Newsletter-Absender',setting('newsletter_sender',''),'email','Erfordert funktionierenden PHP-Mailversand. Kampagnen versenden Sie über Ihren Newsletter-Dienst.'); ?><label class="check-wrap"><input type="checkbox" name="analytics_enabled" value="1" <?= setting('analytics_enabled','0')==='1'?'checked':'' ?>> Öffentliche Seitenaufrufe zählen</label><?php ui_submit(); ?><p class="workspace-note">Veröffentlichungszeiten werden bei jedem Seitenaufruf ausgewertet. Dafür ist kein Cronjob erforderlich. WebCMS <?= e(CMS_VERSION) ?> · Schema <?= e(CMS_SCHEMA_VERSION) ?></p></section><section class="workspace-card"><h2>Öffentliche Schnittstellen</h2><p class="workspace-note">Nur veröffentlichte öffentliche Inhalte werden ausgeliefert. Entwürfe, geschützte Seiten und Formulareinsendungen bleiben intern.</p><?php foreach (['JSON API'=>'/api.php?resource=pages','Nachrichten als JSON'=>'/api.php?resource=entries&kind=news','RSS'=>'/feed.php?format=rss','iCalendar'=>'/feed.php?format=ics','Sitemap'=>'/sitemap.php'] as $label=>$url) echo '<p>'.ui_link($label,$url).'</p>'; ?></section></div></div>
    <section class="workspace-card"><h2>Aktivitätsprotokoll</h2><ul class="activity-list"><?php foreach (cms_rows('SELECT a.*,u.username FROM activity_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 50') as $a): ?><li><?= e($a['description']??'') ?><small><?= e($a['created_at'].' · '.($a['username']??'System').' · '.$a['action']) ?></small></li><?php endforeach; ?></ul></section><?php
endif; ui_end();
